name: Java Library CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3. Build the project (Gradle)
      - name: Build JAR
        run: ./gradlew clean build

      # 4. Verify JAR file exists
      - name: Verify JAR
        run: ls -lh build/libs

      # 5. Upload JAR as workflow artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-java-library
          path: build/libs/*.jar

      # Optional: Create GitHub release and upload JAR
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/my-library.jar
          asset_name: my-library.jar
          asset_content_type: application/java-archive
